<robot name="turtle-bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="materials.urdf.xacro"/>
    <xacro:property name="turtle_config" value="${xacro.load_yaml('$(find turtle_brick)/config/turtle.yaml')}"/>

    <xacro:property name="wheel_radius" value="${turtle_config['turtle_robot']['ros__parameters']['wheel_radius']}"/>
    <xacro:property name="platform_height" value="${turtle_config['turtle_robot']['ros__parameters']['platform_height'] - wheel_radius*2}"/>
    <xacro:property name="cylinder_length" value="${0.4*platform_height}" />
    <xacro:property name="base_length" value="${0.4*platform_height}" />
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_length} ${base_length}" />
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_length} ${base_length}" />
            </geometry>
        </collision>
    </link>

    
    <link name="cylinder_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${cylinder_length}" radius="0.2"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${cylinder_length}" radius="0.2" />
            </geometry>
        </collision>
    </link>

    <xacro:property name="platform_length" value="0.2" />
    <link name="platform_link">
        <visual>
            <origin xyz="0 0 ${platform_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${platform_length}" radius="2"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${platform_length}" radius="2"/>
            </geometry>
        </collision>
    </link>

    <xacro:property name="stem_length" value="${platform_height*0.2}"/>
    <link name="stem_link">
        <visual>
            <origin xyz="0 0 ${-stem_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${stem_length}" radius="0.5"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${-stem_length}" radius="0.65"/>
            </geometry>
        </collision>
    </link>

    
    <xacro:property name="wheel_length" value="0.5"/>
    <link name="wheel_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="cylinder_joint" type="fixed">
        <origin xyz="0 0 ${cylinder_length/2 + base_length/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="cylinder_link"/>
    </joint>

    <joint name="platform_joint" type="revolute">
        <origin xyz="0 0 ${cylinder_length/2}" rpy="0 0 0"/>
        <parent link="cylinder_link"/>
        <child link="platform_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="${pi*2}" effort="100" velocity="100"/>
    </joint>

    <joint name="stem_joint" type="revolute">
        <origin xyz="0 0 ${-base_length/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="stem_link"/>
        <axis xyz="0 0 1"/>
        <limit lower="0" upper="${pi*2}" effort="100" velocity="100"/>
    </joint>

    <joint name="wheel_joint" type="revolute">
        <origin xyz="0 0 ${-wheel_radius-stem_length}" rpy="0 0 0" />
        <parent link="stem_link"/>
        <child link="wheel_link"/>
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="${pi*2}" effort="100" velocity="100"/>
    </joint>

    
</robot>